CREATE TYPE ACCOUNT_ROLE AS ENUM ('USER', 'ADMIN');

CREATE TYPE GAME_MODE AS ENUM ('PVE', 'PVP');

CREATE TABLE account
(
    id        SERIAL         NOT NULL PRIMARY KEY,
    email     VARCHAR(255)   NOT NULL UNIQUE,
    roles     ACCOUNT_ROLE[] NOT NULL DEFAULT ARRAY ['USER']::ACCOUNT_ROLE[],
    game_mode GAME_MODE      NOT NULL DEFAULT 'PVE'::GAME_MODE
);