name: Build and Publish docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Build with gradle
        run: ./gradlew clean bootJar -P"vaadin.productionMode=true"
      - name: Build docker image
        run: ./gradlew buildDockerImage
      - name: Push docker image
        run: ./gradlew pushDockerImage
